### ISSUE TITLE
Did you try to connect your React app with Tizen Web Device API ?

### ISSUE THREAD

**Issue by Guidogl** [rovale/react-tizen-watch#115]
I would like to build React app for Tizen TV but I am having difficulties accessing Tizen Web Device API in my app. When try to build it in Tizen studio, I just add `<script type="text/javascript" src="$WEBAPIS/webapis/webapis.js"></script>` and I can access API methods by simply writing `webapis.network.getVersion();` but how to do it in React app?

**Comment by rovale** [comment]
I think you can just add the script reference in `public/index.html`.
