### ISSUE TITLE
Author Signature file not found.

### ISSUE THREAD

**Issue by SatyaSujitPasupuleti** [rovale/react-tizen-watch#117]
When I run deploy.ps1, I get the following warnings
Warning: Not found tizen signature file
Warning: Not found tizen author signature file,
which result in a signature error. 
I already have created a Samsung account profile , checked that the time on the watch is the same as my computer and my phone. 
When I try to change the profiles.xml path using "tizen cli-config "default.profiles.path=C:\tizen-studio\tools\ide\conf\profiles.xml"" it gives me a key:value error. Any ideas on how to fix this issue? I am on windows if that helps. Tizen Studio (not cli)  lets me deploy a normal webapp to my watch.

**Comment by nemethmik** [comment]
Exactly the same issue here. If and when I find a solution, I'll let you know.

**Comment by nemethmik** [comment]
I know why is that. In the deploy.ps1 file find the line
tizen package --type wgt --sign develop -- $buildResultFolder
Replace the word develop with the profile name you used when you created your own profile. Mine is called tizencertificate, for example. To find out your profile name from the profiles.xml run the command:
tizen security-profiles list
I hope this helps, Miklos

**Comment by SatyaSujitPasupuleti** [comment]
Fixed my issue, thank you!
