### ISSUE TITLE
CORS error when trying to connect demo.pimatic.org

### ISSUE THREAD

**Issue by nemethmik** [rovale/react-tizen-watch#119]
Hi Ronald,
Excellent example. I've learned a lot.
![image](https://user-images.githubusercontent.com/38420170/78367049-c0ae2e80-75c1-11ea-920f-493756199a60.png)
When running the application, Fetching is not going away, possibly because of the CORS issue.
Thank you and all the best,
Miklos

**Comment by nemethmik** [comment]
I built and deployed the application on my emulator, and the watch behavior was exactly the same, unfortunately.

**Comment by Asone** [comment]
@nemethmik : works like a charm when testing the application, i don't undestand why it does not work on your side. 

However i've been having CORS policy errors when adding code to fetch data from another domain ( kraken.com ). I've solved the problem prepending `https://cors-anywhere.herokuapp.com/` to the URI i wanted to use.
